name: books_demo
description: See books demo application.
version: 1.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State
  provider: ^6.0.3

  # Screen Route Manager
  auto_route: ^4.0.1
  
  # Network
  http: ^0.13.4

# Json Helper
  json_annotation: ^4.5.0

  # Screen Notifier
  fluttertoast: ^8.0.9
  
  # Localization Helper
  intl: ^0.17.0

  # Responsive Design Helper
  responsive_framework: ^0.2.0



dev_dependencies:
# Generator Engine
  build_runner: ^2.1.11

# Code Generators
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0

    # Lints
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


